import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft, ShieldAlert } from 'lucide-react';
import { createSupabaseServerClient } from '@/lib/supabase/server';
import { requireUser } from '@/lib/auth';
import { EmptyState } from '@/components/ui';
import { PrintButton } from '../../custody/PrintButton';
import { MarkupOverlay, type Shape } from '@/components/media/ImageMarkup';

export const metadata = { title: 'Media log' };

/**
 * A media log: the chosen files, numbered, with their captions and dates.
 *
 * Printed by the browser for the same reason the custody document is — it
 * produces a correct, selectable document with no PDF library. The log stores
 * ids rather than copies, so this page reads the files as they are now. A file
 * deleted since the log was generated is shown as a numbered gap rather than
 * dropped, because a log that silently renumbers itself is not a record.
 */
export default async function MediaLogPage({
  params,
}: {
  params: { id: string; logId: string };
}) {
  const user = await requireUser();
  if (!user.activeOrg) {
    return <EmptyState icon={ShieldAlert} title="You are not a member of any organisation" />;
  }

  const supabase = createSupabaseServerClient();

  const [{ data: log }, { data: kase }] = await Promise.all([
    supabase
      .from('media_log_reports')
      .select('id, title, media_ids, generated_at, generated_by')
      .eq('id', params.logId)
      .eq('case_id', params.id)
      .maybeSingle(),
    supabase
      .from('case_list_view')
      .select('case_number, title, case_type_name, lead_investigator_name')
      .eq('id', params.id)
      .maybeSingle(),
  ]);

  if (!log || !kase) notFound();

  const ids = (log.media_ids as string[]) ?? [];

  const [{ data: files }, { data: author }] = await Promise.all([
    ids.length
      ? supabase
          .from('media_files')
          .select('id, file_name, mime_type, size_bytes, caption, tags, captured_at, uploaded_at, storage_path, bucket, annotations')
          .in('id', ids)
      : Promise.resolve({ data: [] as Record<string, unknown>[] }),
    log.generated_by
      ? supabase.from('users').select('full_name').eq('id', log.generated_by as string).maybeSingle()
      : Promise.resolve({ data: null }),
  ]);

  const byId = new Map((files ?? []).map((f) => [f.id as string, f]));

  // Signed URLs so the images actually appear in the printed document. An hour
  // is long enough to review and print, short enough that a shared page decays.
  const imagePaths = (files ?? [])
    .filter((f) => ((f.mime_type as string) ?? '').startsWith('image/'))
    .map((f) => f.storage_path as string);

  const urls = new Map<string, string>();
  if (imagePaths.length) {
    const { data: signed } = await supabase.storage
      .from('case-media')
      .createSignedUrls(imagePaths, 3600);
    for (const s of signed ?? []) {
      if (s.signedUrl && s.path) urls.set(s.path, s.signedUrl);
    }
  }

  const printedAt = new Date();

  return (
    <div className="mx-auto max-w-3xl space-y-5">
      <div className="flex items-center justify-between gap-3 print:hidden">
        <Link
          href={`/cases/${params.id}?tab=library`}
          className="inline-flex items-center gap-1.5 text-sm text-ink-secondary hover:text-ink"
        >
          <ArrowLeft className="h-3.5 w-3.5" aria-hidden="true" />
          Back to the case
        </Link>
        <PrintButton />
      </div>

      <article className="space-y-5 rounded-lg border border-edge bg-raised p-6 print:rounded-none print:border-0 print:p-0">
        <header className="border-b border-edge pb-4">
          <p className="text-2xs font-medium uppercase tracking-widest text-ink-muted">Media log</p>
          <h1 className="mt-1 text-xl font-semibold text-ink">{log.title as string}</h1>
          <p className="tabular mt-0.5 font-mono text-sm text-ink-secondary">
            {kase.case_number as string}
            {kase.title ? ` — ${kase.title as string}` : ''}
          </p>

          <dl className="mt-3 grid grid-cols-2 gap-x-6 gap-y-1.5 text-sm sm:grid-cols-3">
            <Row label="Case type" value={kase.case_type_name as string} />
            <Row
              label="Lead investigator"
              value={(kase.lead_investigator_name as string) ?? 'Not assigned'}
            />
            <Row label="Files" value={String(ids.length)} />
            <Row
              label="Log generated"
              value={new Date(log.generated_at as string).toLocaleString()}
            />
            <Row label="Generated by" value={(author?.full_name as string) ?? 'Unknown'} />
            <Row label="Document printed" value={printedAt.toLocaleString()} />
          </dl>
        </header>

        {ids.length === 0 ? (
          <p className="py-8 text-center text-sm text-ink-muted">This log contains no files.</p>
        ) : null}

        <ol className="space-y-5">
          {ids.map((id, i) => {
            const f = byId.get(id);

            if (!f) {
              return (
                <li key={id} className="break-inside-avoid border-b border-edge pb-4 last:border-0">
                  <p className="tabular font-mono text-sm font-semibold text-ink">
                    {String(i + 1).padStart(2, '0')}
                  </p>
                  <p className="mt-1 text-sm text-danger">
                    This file has been deleted from the case since the log was generated.
                  </p>
                </li>
              );
            }

            const path = f.storage_path as string;
            const url = urls.get(path);
            const tags = (f.tags as string[]) ?? [];

            return (
              <li key={id} className="break-inside-avoid border-b border-edge pb-4 last:border-0">
                <div className="flex flex-wrap items-baseline gap-2">
                  <span className="tabular font-mono text-sm font-semibold text-ink">
                    {String(i + 1).padStart(2, '0')}
                  </span>
                  <span className="text-sm text-ink">{f.file_name as string}</span>
                </div>

                {url ? (
                  <div className="relative mt-2 overflow-hidden rounded border border-edge bg-sunken">
                    {/* eslint-disable-next-line @next/next/no-img-element -- signed
                        storage URL; the image loader would need a per-project host */}
                    <img
                      src={url}
                      alt={(f.caption as string) ?? (f.file_name as string)}
                      className="max-h-80 w-full object-contain"
                    />
                    {/* Mark-up prints with the photograph — an arrow at the seat
                        of a fire is the point of putting it in the log. */}
                    <MarkupOverlay shapes={((f.annotations as unknown[]) ?? []) as Shape[]} />
                  </div>
                ) : null}

                {f.caption ? (
                  <p className="mt-2 text-sm text-ink">{f.caption as string}</p>
                ) : (
                  <p className="mt-2 text-sm italic text-ink-muted">No caption recorded.</p>
                )}

                <dl className="mt-1.5 grid grid-cols-2 gap-x-6 gap-y-1 text-xs sm:grid-cols-4">
                  <Row
                    label="Captured"
                    value={f.captured_at ? new Date(f.captured_at as string).toLocaleString() : '—'}
                    small
                  />
                  <Row
                    label="Added to case"
                    value={new Date(f.uploaded_at as string).toLocaleString()}
                    small
                  />
                  <Row label="Type" value={(f.mime_type as string) ?? '—'} small />
                  <Row label="Tags" value={tags.join(', ') || '—'} small />
                  <Row
                    label="Mark-up"
                    value={
                      ((f.annotations as unknown[]) ?? []).length === 0
                        ? 'None'
                        : `${((f.annotations as unknown[]) ?? []).length} mark(s), drawn over the original`
                    }
                    small
                  />
                </dl>
              </li>
            );
          })}
        </ol>

        <footer className="border-t border-edge pt-3 text-2xs text-ink-muted">
          Printed from Forensibus on {printedAt.toLocaleString()} by{' '}
          {user.fullName ?? user.email}. Each entry above is reproduced from the case library for{' '}
          {kase.case_number as string}; the system separately records who added each file and when.
        </footer>
      </article>
    </div>
  );
}

function Row({ label, value, small }: { label: string; value: string; small?: boolean }) {
  return (
    <div>
      <dt
        className={
          small ? 'text-2xs text-ink-muted' : 'text-2xs uppercase tracking-wide text-ink-muted'
        }
      >
        {label}
      </dt>
      <dd className={small ? 'break-words text-xs text-ink' : 'text-sm text-ink'}>{value}</dd>
    </div>
  );
}
